{% set name = "arviz-plots" %}
{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arviz_plots-{{ version }}.tar.gz
  sha256: e8bb70824b50f09f7c527dac4519aef1b72cb0a9eadcd4da25b80c22a4bcef71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - arviz-base >=1.0,<1.1
    - arviz-stats >=1.0,<1.1

test:
  imports:
    - arviz_plots
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/arviz-plots
  summary: ArviZ-plots provides ready to use and composable plots for Bayesian Workflow.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://arviz-plots.readthedocs.io
  dev_url: https://github.com/arviz-devs/arviz-plots

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
