{% set name = "arviz-plots" %}
{% set version = "0.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arviz_plots-{{ version }}.tar.gz
  sha256: 4fd492cd70442a742278154ee7ef33e1a38b519fb7a7a750a196c33e48541043

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - arviz-base ==0.6.0
    - arviz-stats ==0.6.0

test:
  imports:
    - arviz_plots
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/arviz-plots
  summary: ArviZ-plots provides ready to use and composable plots for Bayesian Workflow.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://arviz-plots.readthedocs.io
  dev_url: https://github.com/arviz-devs/arviz-plots

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
