schema_version: 1

context:
  name: arviz-plots
  version: 1.1.0
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/arviz_plots-${{ version }}.tar.gz
  sha256: c2d213364c5eaadfe890b1f871849d4317dec5260f79f26e30976159c132a351

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - arviz-base >=1.1,<1.2
    - arviz-stats >=1.1,<1.2
tests:
  - python:
      imports:
        - arviz_plots
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  summary: ArviZ-plots provides ready to use and composable plots for Bayesian Workflow.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://python.arviz.org/projects/plots/en/stable
  homepage: https://www.arviz.org
  repository: https://github.com/arviz-devs/arviz-plots

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
    - tomicapretto
